# Base configs
#https://netoleal.photos
baseurl: ""
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-40563627-3"

collections:
  - albums

# UI configs
title: "Neto Leal | Fotografia"
subtitle: "See the world through my eyes!"
author: "Neto Leal"
header:
 title: "Neto Leal"
 subtitle: "Arte e Fotografia"
footer:
 name: "Opa! Beleza?"
 bio: "Sou Neto. Passei 20 anos trabalhando com tecnologia e desenvolvimento de softwares até descobrir que estava infeliz e que precisava ter mais espaço na minha vida para a minha paixão pela fotografia. Para mim a arte está em cada momento. Capturar aquela fração de segundo e eternizar em uma imagem cheia de emoções e sentimentos. Fotografar é olhar o mundo com outros olhos. É descobrir formas, cores, luzes em lugares improváveis. É ver beleza em qualquer lugar. É música em forma de imagem."
 github: ""
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/lealneto"
  # twitter: "https://www.twitter.com/netoleal"
  instagram: "https://www.instagram.com/glealneto"
  linkedin: "https://in.linkedin.com/in/netoleal"
  
